name: linguist
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_tts: ^1.2.2
  image_picker: ^0.6.6+4
  firebase_ml_vision: ^0.9.3+8
  http: ^0.12.0+2
  firebase_mlkit_language: ^1.1.2
  image_cropper: ^1.2.3
  speech_to_text: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/